#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible-role-wordpressleboss

- name: restart apache
  service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted
